- LICENSE.md
- build_sdk.py
- adjust build_sdk for file rename
- adjust license file text so that it works for both repo and SDK
> LICENSE file adjustments

- monitor/src/main.c
I don't agree with these style checks (particularly the switch case style) but I don't have the energy to fight the system on something that is ultimately meaningless.
> monitor: adhere to CI style checks

- docs/manual.md
I am slightly worried about this repeatedly out-of-date, however, in the past year or so of Microkit development, the Microkit tool usage has not changed much (if at all).
> manual: update tool usage and description

- monitor/src/main.c
The current code prints a false-positive error because it prints an error *before* checking if it was a passive PD giving up its scheduling context.
> Fix printing in monitor when dealing with passive PDs

- loader/src/loader.c
Hopefully the last one of these I have to make.
> loader: adhere to CI style checks

- libmicrokit/include/microkit.h
Needed for https://github.com/seL4/microkit/pull/120.
> libmicrokit: style

- tool/microkit/src/main.rs
- Fix handling of PD names longer than 16 bytes
- Fix some cases of incorrect constants being used
> Fix some bugs in the new tool

- tool/microkit/src/lib.rs
Also fixes the relevant conditional expression.
> tool: fix off-by-one error

- docs/manual.md
- loader/src/loader.c
Motivated by getting the ZCU102 working on mainline QEMU. Thanks to @nspin for bringing this up.
> Fixes relating to the ZCU102

- libmicrokit/include/microkit.h
Change `microkit_channel ch` parameter to `microkit_pd pd`.
> libmicrokit: fix declaration for `fault()`

- docs/manual.md
> manual: fix typo

- .github/workflows/pr.yml
- tool/microkit/src/elf.rs
- tool/microkit/src/lib.rs
- tool/microkit/src/loader.rs
- tool/microkit/src/main.rs
- tool/microkit/src/sel4.rs
- tool/microkit/src/sysxml.rs
- tool/microkit/src/util.rs
- tool/microkit/tests/test.rs
Addresses https://github.com/seL4/microkit/issues/160
> tool: Apply `rustfmt` and add `cargo fmt --check` to PR workflow

- tool/microkit/src/sdf.rs
- tool/microkit/tests/sdf/pd_duplicate_setvar.xml
- tool/microkit/tests/test.rs
Also adds a test for the error message.
Closes https://github.com/seL4/microkit/issues/176.
> tool: check for duplicate setvars

- docs/manual.md
- libmicrokit/src/crt0.s
- libmicrokit/src/main.c
- tool/microkit/src/main.rs
- tool/microkit/src/sdf.rs
- tool/microkit/src/sel4.rs
- tool/microkit/tests/sdf/pd_small_stack_size.xml
- tool/microkit/tests/sdf/pd_unaligned_stack_size.xml
- tool/microkit/tests/test.rs
Closes https://github.com/seL4/microkit/issues/98.
> Add ability to configure stack size for PDs

- tool/microkit/src/main.rs
This patch is, thankfully, fairly simple and enables users to allocate MRs at a fixed address that relies in normal memory.
The primary motivation for doing such a thing is 1-1 mappings between the guest and hypervisor to enable DMA capable guest drivers.
Closes https://github.com/seL4/microkit/issues/172.
> tool: fix allocation of fixed MRs from normal memory

- CHANGES.md
Depends on a number of PRs being merged.
> Add release notes for 1.4.0

- tool/microkit/src/main.rs
- tool/microkit/src/sel4.rs
Wanja told me that you can just index into HashMaps as well as arrays...
> tool: do not use .get with .unwrap

- README.md
- build_sdk.py
- docs/manual.md
- example/rockpro64/hello/Makefile
- example/rockpro64/hello/hello.c
- example/rockpro64/hello/hello.system
- loader/src/loader.c
Replaces https://github.com/seL4/microkit/pull/71.
> Add support for Pine64 RockPro64

- tool/microkit/src/sdf.rs
Forgot to do this for virtual machines as well.
> tool: check for valid mappings in virtual machines

- tool/microkit/tests/sdf/pd_duplicate_child_id_vcpu.xml
- tool/microkit/tests/sdf/vm_duplicate_name.xml
- tool/microkit/tests/sdf/vm_invalid_vcpu_cpu.xml
- tool/microkit/tests/sdf/vm_invalid_vcpu_id.xml
- tool/microkit/tests/sdf/vm_missing_mr.xml
- tool/microkit/tests/sdf/vm_missing_vcpu.xml
- tool/microkit/tests/sdf/vm_missing_vcpu_id.xml
- tool/microkit/tests/sdf/vm_not_child.xml
- tool/microkit/tests/sdf/vm_overlapping_maps.xml
- tool/microkit/tests/test.rs
Closes https://github.com/seL4/microkit/issues/239.
> tool: add tests for parsing virtual machines

- monitor/src/main.c
- monitor/src/util.c
- tool/microkit/src/main.rs
- tool/microkit/src/sdf.rs
Closes https://github.com/seL4/microkit/issues/235.
> Utilise seL4_DebugNameThread for debugging

- README.md
Forgot to do in the PR adding Cheshire support.
> README: mention Cheshire

- README.md
- build_sdk.py
- docs/manual.md
- loader/src/loader.c
- tool/microkit/src/lib.rs
- tool/microkit/src/main.rs
- tool/microkit/src/sel4.rs
Closes https://github.com/seL4/microkit/issues/219.
> Add support for Raspberry Pi 4B

- docs/manual.md
- tool/microkit/src/main.rs
- tool/microkit/src/sdf.rs
Closes https://github.com/seL4/microkit/issues/99.
> Add 'setvar_size' attribute for MR mappings

- docs/manual.md
* typo and styling fixes
* expand on how entry points are executed with relation to scheduling
Closes https://github.com/seL4/microkit/issues/142.
> manual: various fixes/improvements

- build_sdk.py
Signed-off-by: Yanfeng Liu <yfliu2008@qq.com>
> Fix typo in build_sdk.py

- docs/manual.md
- platfroms.yml
See the file itself for more info, but basically this is part of the seL4 docs-site redesign and now that it is live I am moving this file into the Microkit repo itself rather than being in the docs repo.
> platforms.yml: init
