- tool/sel4coreplat/__main__.py
Without this change this causes issues when trying to use a 2MiB page size with a region that's larger than 2MiB since the call to `allocate_fixed_objects` is using whatever `page_size` was last set as, rather than what the current memory region's page size is.
> Use correct memory region page size

- tool/sel4coreplat/sel4.py
The `seL4_ARM_Page_Map` invocation takes in the page attributes after the page rights. The seL4CP tool that creates the invocations has the correct order so it does not need to change, but because the invocation's fields in the wrong order, the actual invocations that were being generated were wrong.
> Fix order of attributes and rights fields in Sel4PageMap invocation

- monitor/src/main.c
I have personally found this useful when adding support for a certain platform/board.
> Improve monitor error messages on boot info mismatch

- docs/manual.md
- tool/sel4coreplat/sysxml.py
- tool/test/__init__.py
- tool/test/ch_id_greater_than_62.xml
- tool/test/irq_id_greater_than_62.xml
- tool/test/irq_id_less_than_0.xml
This PR does two things.
1. Fixes the max ID for a channel end to be 62 instead of 63. This is because the last bit of the badge is used to distinguish on whether we have received an PPC or a notification. Having the max ID as 63 will mean this bit is overwritten and so notifying a channel with an ID of 63 will instead be delivered as a PPC.
2. Applies the same fix to IRQs and adds tests like for channel IDs.
3. Makes a note of the valid channel/IRQ IDs in the manual.
> Fix max ID checks on channels/IRQs

- docs/manual.md
- tool/sel4coreplat/sysxml.py
- tool/test/__init__.py
- tool/test/pd_write_only_mr.xml
On all architectures that seL4 currently supports, write-only mappings are not allowed. It is preferable to catch these at build-time rather than having an error at run-time.
> Add error checking for write-only memory region mappings

- build_sdk.py
The standalone seL4 kernel ELF does not successfully build for the i.MX8MM-EVK. This is fixed in a later version of seL4. In the interest of having the SDK build, we temporarily disable building the SDK for this platform.
I do not have access to the seL4 repository that the SDK uses and hence cannot fix the source of the issue at this moment.
> Temporarily disable i.MX8MM-EVK support

- README.md
All the other commands use `./pyenv` instead of `./env` so when copy+pasting the commands to run it breaks the flow,
> Make use of pyenv consistent in README

- libmicrokit/src/dbg.c
- monitor/src/util.c
It should be `CONFIG_PRINTING` as a debug build of the kernel does not necessarily have printing enabled (although this is a rare case and I only ran into it when debugging something with a debug kernel with printing intentionally disabled).
> Fix config option used in ifdef for seL4 debug printing

- .github/workflows/pr.yml
- .github/workflows/push.yml
- .gitignore
- LICENSES/BSD-2-Clause.txt
- LICENSES/CC-BY-SA-4.0.txt
- README.md
- build_sdk.py
- dev_build.py
- docs/README.md
- docs/manual.md
- example/imx8mm/passive_server/client.c
- example/imx8mm/passive_server/server.c
- tests/capfault/README.md
- tests/overlapping_pages/README.md
- tests/simplemrs/README.md
- tool/microkit/docs.md
This PR adds the basic standard checks for foundation repos:
- licenses
- trailing whitespace
- gitlint
- code style
- portable shell check
- link check (for links in .md and .html files)
It also adds missing license headers and texts so that the licence check can succeed on new pull requests.
The style check is likely to fail initially if the repo hasn't used the same `astyle` config before. We can leave that check as optional for a while of that leads to friction.
> basic foundation CI setup

- dev_build.py
Both these arguments are required, invoking the `dev_build.py` script without them causes a confusing error. This patch fixes that.
> Making board and example arguments in dev_build.py required

- .github/workflows/sdk.yaml
This patch attempts to bring basic CI to seL4CP. Currently, it only builds the SDK and then uploads the artefact for anyone to be able to download.
An example of a CI run is here: https://github.com/Ivan-Velickovic/sel4cp/actions/runs/4602867006.
There are some costs to consider with using GitHub provided CI however.
* They run in a virtualised environment, with other dependencies already installed and possibly other configuration that does not match the environment that a developer would use when building/using the SDK.
* It is quite slow, takes about 5-6 minutes on a GitHub runner vs about one minute on my personal computer. Some of this time is due to having to install the dependencies each time the CI is run, which might actually be a good thing.
* One of the issues I generally have …
> Add basic CI

- build_sdk.py
The seL4 build system is configured to find installations of compilers on the host, meaning that the `aarch64-none-elf-` toolchain that we use might not be used when building seL4 depending on what other toolchains are installed.
> Use specific AArch64 toolchain when compiling seL4

- build_sdk.py
The `board.name` may not actually be the name of a valid seL4 platform so this is wrong, in addition `KernelPlatform` is provided by each supported platform's kernel options.
> Remove redundant `-DKernelPlatform` when building seL4

- .github/workflows/sdk.yaml
gcc-aarch64-linux-gnu is no longer required as we use the aarch64-none-elf toolchain for compiling everything since cb849f7695a39d3e0a9e2b34f7c9e360992a8883.
> ci: remove unnecessary dependency

- dev_build.py
Useful for debugging/testing the release configuration.
> dev_build: add option to explicitly pass config

- docs/manual.md
This one slipped past the commit that renamed everything due to being a typo.
> manual: fix missing rename to Microkit

- docs/manual.md
Closes https://github.com/seL4/microkit/issues/82.
> Minor fixes to manual

- libmicrokit/Makefile
- loader/Makefile
- monitor/Makefile
More recent versions of `aarch64-none-elf-as` don't support passing a debug level to `-g`.
Specifically, GNU Binutils 2.40 (associated with GCC 12.3) doesn't support this.
> Omit assembler debug level to improve toolchain compatability

- docs/manual.md
Fixes spelling mistakes and adds instructions for booting on ZCU102 hardware. Closes https://github.com/seL4/microkit/issues/30.
In the future we need to find out how to integrate the documentation for each board with the official seL4 documentation. Including how to setup U-Boot etc is too much for the Microkit manual most likely but I still believe that the manual should include instructions specific to Microkit should remain in the manual.
> Minor manual fixes

- example/imx8mm/passive_server/client.c
- example/imx8mm/passive_server/server.c
Making the style consistent with other examples and fixing the server code such that it prints the right message when getting a PPC from the client.
> Fixes and cleanup in passive server example

- docs/manual.md
Closes https://github.com/seL4/microkit/issues/48.
> manual: add initial guide for platform ports

- tool/microkit/__main__.py
Before:
```
0x001f TCB                  - WriteRegisters    - 0x8000000000000006 (TCB: PD=hello)
resume               False
arch_flags           0
regs                 <microkit.sel4.Sel4Aarch64Regs object at 0x7f4eeed85880>
```
After:
```
0x001f TCB                  - WriteRegisters    - 0x8000000000000006 (TCB: PD=hello)
resume               False
arch_flags           0
regs                 pc: 0x0000000000200000
sp: 0x0000000000000000
spsr: 0x0000000000000000
x0: 0x0000000000000000
x1: 0x0000000000000000
x2: 0x0000000000000000
x3: 0x0000000000000000
x4: 0x0000000000000000
x5: 0x0000000000000000
x6: 0x0000000000000000
x7: 0x0000000000000000
x8: 0x0000000000000000
x16: 0x0000000000000000
x17: 0x0000000000000000
x18: 0x0000000000000000
x29: 0x0000000000000000
x30: 0x0000000000000000
x9: …
```
> tool: print out values of TCB registers in report

- build_sdk.py
- libmicrokit/Makefile
- libmicrokit/microkit.ld
LLD does not recognise the STARTUP directive which works with the GNU linker. Given that the crt0.s entry point is already specified to be at the start of the _text section when linking with libmicrokit, all we need to do is slightly change the Makefile to also include crt0.o when linking to produce libmicrokit.a
> libmicrokit: fix to successfully link on LLD

- tool/microkit/__main__.py
Correctly handle PD segments whose start vaddrs do not lie on page boundaries.
> tool: Handle unaligned PD segments

- tool/microkit/__main__.py
- tool/microkit/elf.py
- tool/microkit/loader.py
- tool/microkit/sel4.py
- tool/microkit/sysxml.py
- tool/microkit/util.py
- tool/test/__init__.py
Ran `seL4_tools/misc/style-all.sh` on the whole repository, so hopefully this is the last PR of this kind we have to make.
> tool: adhere to CI style checks

- monitor/src/main.c
To enable protection domains with larger memory footprints.
https://github.com/seL4/rust-microkit-http-server-demo, for example, requires at least 122 `seL4_Word`s.
> monitor: Increase BOOTSTRAP_INVOCATION_DATA_SIZE

- README.md
- tool/microkit/__main__.py
- tool/microkit/sel4.py
There are a couple of breaking changes to seL4 which affect the Microkit tool.
* The size of seL4_MinSchedContextBits changing
* The addition of the ARM SMC forwarding invocation
* The change to page table invocations for AArch64
> Update to latest seL4

- tool/microkit/util.py
I believe the variable `max_bits` corresponds to `seL4_MaxUntypedBits`. The value of this on AArch64 is 47 (see `seL4/libsel4/sel4_arch_include/aarch64/sel4/sel4_arch/constants.h`.
I have not run into issues because this value is not correct yet, but I thought I would try to fix it before having to debug something going wrong.
> Fix value of seL4_MaxUntypedBits when emulating kernel boot

- .github/workflows/sdk.yaml
- README.md
- build_sdk.py
- example/imx8mm_evk/passive_server/Makefile
- example/maaxboard/hello/Makefile
- example/tqma8xqp1gb/ethernet/Makefile
- example/zcu102/hello/Makefile
- libmicrokit/Makefile
- loader/Makefile
- monitor/Makefile
- requirements.txt
- tests/capfault/Makefile
- tests/overlapping_pages/Makefile
- tests/simplemrs/Makefile
It would be sad to force macOS users to have to dual boot or use a Docker container in order to use the Microkit SDK. These patches add macOS support to the Microkit SDK and have received internal use at TS for a while now so I think it's fair to say that the macOS support will be stable.
Couple of things left to do:
> Add macOS support

- docs/manual.md
- tool/microkit/__main__.py
- tool/microkit/sel4.py
- tool/microkit/sysxml.py
- tool/test/__init__.py
- tool/test/irq_invalid_trigger.xml
Currently all interrupts are registered as level-triggered, this patch enables users to specify a interrupt in the system description as edge-triggered instead.
One alternative solution would be to look at the device tree for the interrupt trigger type instead.
> Add option to declare IRQ as "edge" triggered

- requirements.txt
Unfortunately it seems that multiple people in the community are struggling to build from source after we upgraded to the latest version of Pyoxidizer (same issue as https://github.com/seL4/microkit/issues/37)
This seems to be a known issue in the project
https://github.com/indygreg/PyOxidizer/issues/673.
The nature of this problem comes from our over-reliance on 3rd-party dependencies to package the Microkit tool. We will most likely encounter further issues as we are compiling an interpreted language.
However, even if we were to switch to a compile time langauge (e.g Rust) we would still have problems as the Rust compiler is not isolated.
> Downgrade Pyoxidizer from 0.24.0 to 0.23.0

- .github/workflows/sdk.yaml
NodeJS 16 is deprecated so we have to upgrade
the GitHub actions that depend on it.
> ci: update GitHub actions

- build_sdk.py
PyOxidizer creates a binary with 0o770 permissions.
> Make tool binary world-accessible

- docs/manual.md
- libmicrokit/include/microkit.h
Add a microkit wrapper around seL4_MessageInfo_get_length function.
> libmicrokit: add function to get mr count from msginfo

- docs/manual.md
- libmicrokit/include/microkit.h
- libmicrokit/src/main.c
The headers included in microkit.h depend on the compiler and toolchain, it is beneficial to avoid this if possible as they may not be provided at all depending on the C toolchain or contain subtle differences to what we expect.
Closes https://github.com/seL4/microkit/issues/124.
> libmicrokit: remove dependency on toolchain headers

- .github/workflows/sdk.yaml
- README.md
Dependency on musl is thankfully gone now! While we still use the *-musl targets for the tool that is now rewritten in Rust instead of using Python/pyoxidizer, it is not dependent on the musl-gcc toolchain.
> Remove mention of musl dependency

- tool/microkit/src/lib.rs
- tool/microkit/src/main.rs
Mistakes from the rewrite of the tool.
This should get the ZCU102 working again, which I forgot to test before merging the rewritten tool.
> tool: fix logic bugs

- .github/workflows/pr.yml
- tool/microkit/src/elf.rs
- tool/microkit/src/lib.rs
- tool/microkit/src/loader.rs
- tool/microkit/src/main.rs
- tool/microkit/src/sel4.rs
- tool/microkit/src/sysxml.rs
- tool/microkit/src/util.rs
There is a bunch of code flagged by clippy.
- abb7902fca34ffbfc470e204047bbd6ad56d57a4 is a manual fix for a specific problem flagged by clippy
- 731c204d056729dd11f68f8a85327e6553e98037 adds an allow for something `cargo clippy --fix` would remove automatically
- 2115578eaf331ed124460dfa030f7d6f3c3ac62f automatically fixes most of the issues, it contains precisely the result after `cargo clippy --fix`
- fe8ee09cc082f1b8b06794927f09f024173bbb96 fixes the remaining lints by hand. Some of the issues flagged by clippy are non-issues IMHO, hence I added `#[allow(...)]` statements
- 4e464071017623d23be1a044a326f0783508cbb1 adds  a CI check to point out lints violations in an automated fashion
> chore: apply clippy lints on Rust code

- libmicrokit/include/microkit.h
- libmicrokit/src/main.c
- tool/microkit/src/main.rs
Some variables do genuinely have to be global in libmicrokit and so we make sure they all have a prefix of `microkit_*` to avoid clashing with any user code.
The message registers for passive PD init are not used so we remove those lines.
Closes https://github.com/seL4/microkit/issues/140.
> libmicrokit: minor cleanup/improvements

- build_sdk.py
This PR adds four new options to the `build_sdk.py` CLI:
- `--only-board <board>`: only artifacts for `<board>` will be built
- `--only-config <config>`: only artifacts for `<config>` (either `"debug"` or `"release"`) will be built
- `--skip-docs`: docs will not be built
- `--skip-source-tarball`: source tarball will not be built
These options are useful in cases where the SDK is being built by a build system that doesn't have any use for artifacts other than those necessary for building a particular system.
> build_sdk.py: add support for minimal build

- tool/microkit/src/elf.rs
The current code would build up a map of ELF symbols when
first parsing the ELF for quick lookup later on when we
patch/read certain symbols. In this process if we encounter
a symbol that is already in the map, we error and exit.
This patch changes the error to only happen when a symbol we
care about (because we are either writing to it or reading
from it) occurs multiple times.
This lets us parse ELFs even when they have multiple symbols
with the same name and only error if it actually matters.
This issue was brought up by @nspin.
> tool: fixes for ELF parsing errors

- build_sdk.py
An extension of https://github.com/seL4/microkit/pull/131
Adds the `--skip-tool` flag.
Cargo takes some special care to work in hermetic build environments such as Nix. One good way to deal with all such cases at once is to provide the option to skip building the tool entirely and allow those more particular build environments to take care of building the tool themselves.
> build_sdk.py: add support for skipping tool

- build_sdk.py
- dev_build.py
- docs/manual.md
- example/qemu_virt_aarch64/hierarchy/restarter.c
- libmicrokit/include/microkit.h
- libmicrokit/src/main.c
- loader/Makefile
- loader/src/loader.c
- loader/src/util64.S
- tool/microkit/Cargo.lock
- tool/microkit/Cargo.toml
- tool/microkit/src/loader.rs
- tool/microkit/src/main.rs
- tool/microkit/src/sel4.rs
- tool/microkit/src/sysxml.rs
- tool/microkit/src/util.rs
- tool/microkit/tests/test.rs
This PR adds support for running seL4 in hypervisor mode as well as
a new 'virtual machine' abstraction.
This commit message says 'initial support' as features such as
multi-vCPU/core support for VMs are not yet implemented. However,
with this patch, we can run guest operating systems such as Linux
on a Microkit system.
Merge checklist:
Post-merge checklist:
*  [ ] Fault handling in the manual could be specified better than just referring to the seL4 reference manual.
> Virtualisation support

- docs/manual.md
This commits adds a note on booting Microkit on the zcu102. In particular, it mentions a fix for situations where the boot fails do to U-Boot switching from EL2 to EL1 just before handing of boot to Microkit.
> feat: add note about Xilinx U-Boot EL1 quirk

- build_sdk.py
Change the permissions to be owner-writeable. This means we no longer need `sudo` to move or remove the SDK after unpacking the tar.
I can't know the original reason for doing this, but I imagine it was to prevent users from accidentally removing the SDK unless they really wanted to.
However, the user-experience of this is poor and in not worth it in my opinion.
Closes https://github.com/seL4/microkit/issues/163.
> Fix SDK permissions

- build_sdk.py
The QEMU virt platform does not have a timer and so the only
way to get a timer driver working is to use the architectural
timer.
Exporting the architectural timer to user-space can be problematic
as it means any user-space program can access it, including ones
you may not trust. However, as this platform is only intended for
development purposes, this is not an issue.
> Export ARM architectural timer for QEMU virt AArch64

- README.md
- build_sdk.py
- docs/manual.md
- libmicrokit/include/microkit.h
- tool/microkit/src/main.rs
- tool/microkit/src/sel4.rs
- tool/microkit/tests/test.rs
This patch adds a new configuration for each platform called 'benchmark'.
The purpose of this is to enable Microkit systems to leverage the benchmark configuration of seL4 that tracks things like kernel entries and CPU utilisation. This also exports the PMU to user-space.
This is not ideal, which is why [RFC-16](https://github.com/seL4/rfcs/pull/22) exists. However, we need to be able to do benchmarking for projects like the seL4 Device Driver Framework in the meantime. It may take a while to get the RFC approved and implemented which is why we are adding this 'temporary' configuration.
[RFC-16]: https://sel4.atlassian.net/browse/RFC-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add 'benchmark' configuration

- build_sdk.py
- loader/Makefile
- loader/src/loader.c
The manual says that the loader should not print on release mode, so this patch just makes that true.
> loader: do not print logs on non-debug mode

- docs/manual.md
- libmicrokit/include/microkit.h
This patch adds two new libmicrokit APIs:
* microkit_deferred_notify
* microkit_deferred_irq_ack
The motivation for this is that the normal versions of these
APIs (e.g microkit_irq_ack) do a system call, and then when you
return from the entry point, another system call is done to wait
on further events.
In the case of `microkit_deferred_irq_ack`, the libmicrokit event
handler will both ack an IRQ and wait for further events in a single
system call.
In the case of `microkit_deferred_notify`, the libmicrokit event
handler will both notify a PD and wait for further events in a single
system call.
In highly performance critical code where there are a lot of events
happening, calling these APIs can significantly
increase performance.
> libmicrokit: add 'deferred' API

- tool/microkit/src/sdf.rs
The commit 556534170c510c8cdac7bdfa6acc0def9f7d8d85 did not actually fix the problem. This commit simplifies the way we are processing parent PDs into a flat list and so should not have any more bugs. This has been tested on more complicated nesting examples and seems to work.
> tool: fix and simplify PD flattening again

- build_sdk.py
Need to add `KernelVerificationBuild` in order to enable utilisation tracking in the kernel.
> Fix benchmark config to track utilisation

- build_sdk.py
- dev_build.py
- tool/microkit/src/elf.rs
- tool/microkit/src/main.rs
- tool/microkit/src/sel4.rs
- tool/microkit/src/util.rs
This PR implements a number of performance improvements to make sure that building a Microkit system feels instantaneous, even for larger systems.
Most of the changes decrease the two main bottlenecks, ELF parsing and dynamic memory allocation (aka `.clone` in Rust).
This PR significantly decreases the performance and memory usage of the tool.
Below is performance numbers for a hello world program (top is after, bottom is before):
```
Benchmark 1 (1530 runs): /home/ivanv/ts/microkit/release/microkit-sdk-1.3.0/bin/microkit example/qemu_virt_aarch64/hello/hello.system --search-path /home/ivanv/ts/microkit/tmp_build --board qemu_virt_aarch64 --config debug -o /home/ivanv/ts/microkit/tmp_build/loader.img -r /home/ivanv/ts/microkit/tmp_build/report.txt
measurement          mean ± σ …
```
> tool: performance improvements

- tool/microkit/src/main.rs
This only revelead itself when building/running a large system with Microkit.
Unfortunately I only ran into this, *after* releasing 1.4.0... :(
> tool: fix bootstrap page table repeat invocation

- build_sdk.py
We are compiling libmicrokit with hardware floating extensions which means that user-code must also be compiled with hardware floating extensions.
This meant that before this patch user programs that make use of floating point instructions would crash as the kernel has the FPU disabled.
Something to fix in a separate PR is making the `-march` and `-mabi` of a platform be described for each platform rather than globally which is what it is now.
> Enable FPU on QEMU virt RISC-V and Star64

- requirements.txt
The motivation is that building the dependency from source with Python3.9 does not work with 6.0 but 6.0.2 works fine. The reason this hasn't been an issue before because everyone has been grabbing the dependencies from wheels.
> Update PyYAML to 6.0.2

- build_sdk.py
This changes the behaviour of virtual machines to see the architectural timer change even when it is not running.
I do not understand why this option applies to all vCPUs in the kernel, instead of being behaviour that depends on the configuration of a particular vCPU.
I tried to learn more about this kernel configuration option in https://github.com/seL4/seL4/issues/1306 but no-one responded.
> Disable 'KernelArmVtimerUpdateVOffset' by default

- tool/microkit/Cargo.toml
The motivation is that 1.79.0 is still quite new so those who want to build all their tools from source with a pinned Rust version can build Microkit from source without upgrading.
Closes https://github.com/seL4/microkit/issues/198.
> tool: make minimum Rust version 1.73.0

- build_sdk.py
- docs/manual.md
- tool/microkit/src/loader.rs
It was seen on larger Microkit systems that the loader data was
overlapping with the code for the loader itself when the loader
attempted to copy the data to the appropriate location before
jumping to seL4 and starting the system.
I believe the root cause of this problem is not gone and will involve
changing the tool to be smarter with how it allocates physical memory,
my current attempts to do so lead to other issues. I'll have to make a
follow up fix to prevent this from happening again, but for now this
will allow users of the MaaXBoard to run larger Microkit systems.
This PR also adds a patch to make sure that if overlapping does occur,
we find it at build time instead of having weird errors at runtime.
> MaaXBoard loader address fix

- tool/microkit/src/util.rs
This usually does not make sense, e.g for normal native programs.
However, in the case of a virtual machine it does actually make sense since sometimes you are trying to emulate hardware where RAM (and hence guest RAM) may start at zero.
This assert was not necessary in the first place.
> Allow mapping in virtual address of zero

- .github/workflows/sdk.yaml
- build_sdk.py
- ci/dev_version.sh
This will be used by CI for builds on each commit of Microkit, which will be useful for getting prebuillt SDKs between official releases.
> Add ability to specify version of SDK

- tool/microkit/src/main.rs
- tool/microkit/src/sdf.rs
- tool/microkit/src/sel4.rs
- tool/microkit/tests/sdf/sys_map_too_high.xml
- tool/microkit/tests/test.rs
This patch checks that a memory mapping is not at a virtual address that is greater than the maximum virtual address.
> Add more error checking for memory mappings

- tool/microkit/src/sdf.rs
This was in the tool before it was rewritten to Rust, the omission of the warning was an oversight when I did the rewrite.
> Re-add warning for unused MRs

- .github/workflows/sdk.yaml
Forgot to cross-compile the Microkit tool to x86-64.
This doesn't affect any of the released artefacts, just the per-commit ones.
> ci: fix macOS x86-64 SDK artefact

- .github/workflows/sdk.yaml
- build_sdk.py
- tool/microkit/.cargo/config.toml
- tool/microkit/Cargo.toml
Rust's cross-compiling is limited so this only works from a Linux host, if you're on macOS it won't work.
> Enable building SDK for Linux AArch64

- .github/workflows/sdk.yaml
- tool/microkit/.cargo/config.toml
I specified the linker to `aarch64-none-elf-ld` because I would've thought that even though we are targeting Linux, the linker shouldn't matter but on Linux AArch64 we get a segfault when running the Microkit tool.
Changing the linker to `aarch64-linux-gnu-ld` fixes that.
I'm not really happy with this solution as we now have to install a new C toolchain just to compile a Rust program, from searching on the internet the solution seems to be to use the cross-rs package, which just uses Docker containers so isn't actually cross compiling anything.
If anyone has any better ideas please let me know.
> Fix linking of tool on Linux AArch64

- libmicrokit/include/microkit.h
- libmicrokit/src/main.c
- monitor/src/main.c
- tool/microkit/src/lib.rs
- tool/microkit/src/main.rs
Also adds a null terminating at the end of the string when patching the monitor's PD name array. This fixes the monitor output when there exists a PD that has a name that exceeds the max name length.
> Increase max PD name length to 64

- libmicrokit/src/main.c
In order to have libmicrokit compiling with PDs that do not provide the 'protected' or 'fault' entry points, we have empty implementations of them.
This has an unfortunate consequence that if a programmer forgets to provide implementations of these entry points, things will silently fail.
> libmicrokit: add error message for entry points not provided

- README.md
- build_sdk.py
Allow building the SDK with a custom toolchain prefix
We will always have an official, 'supported' C toolchain but it has
become apparent that:
1. GCC toolchain triples are a complete, inconsistent mess.
2. People may have vendored toolchains that they must use when compiling
from source.
Therefore, we introduce arguments to the build_sdk.py script that allows
overriding the default prefixes.
Closes https://github.com/seL4/microkit/issues/201.
> Allow building the SDK with a custom toolchain prefix

- docs/manual.md
- tool/microkit/src/main.rs
- tool/microkit/src/sdf.rs
- tool/microkit/tests/sdf/ch_bidirectional_ppc.xml
- tool/microkit/tests/sdf/ch_end_invalid_notify.xml
- tool/microkit/tests/sdf/ch_end_invalid_pp.xml
- tool/microkit/tests/sdf/ch_invalid_element.xml
- tool/microkit/tests/sdf/ch_not_enough_ends.xml
- tool/microkit/tests/sdf/ch_ppcall_priority.xml
- tool/microkit/tests/sdf/ch_too_many_ends.xml
- tool/microkit/tests/test.rs
Also fixes #168, as this allows us enough precision to check priorities.
Can specify `pp="true"` or `notify="false"` (or vice-versa, for the defaults):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<system>
<protection_domain name="test1">
<program_image path="test" />
</protection_domain>
<protection_domain name="test2">
<program_image path="test" />
</protection_domain>
<channel>
<end pd="test1" id="0" pp="true" notify="false" />
<end pd="test2" id="5" />
</channel>
</system>
```
ToDo:
> Allow specifying notify or ppcalls on a per-channel, not per-protection domain basis

- build_sdk.py
- tool/microkit/src/main.rs
- tool/microkit/src/sel4.rs
- tool/microkit/tests/test.rs
Instead of hard-coding invocation numbers, we now
get them from a file generated by the seL4 kernel
build.
Depends on: [bd1c39240944207ef71237f98663acb06cc971f6](https://github.com/seL4/seL4/commit/bd1c39240944207ef71237f98663acb06cc971f6)
> Load invocation numbers from JSON file

- flake.nix
We want the unwrapped bintools so we don't have weird extra arguments such as '-liconv'. iconv doesn't exist on macOS by default I believe so we were encountering 'library not found' errors even though the Nix flake on Linux was working fine.
> Fix bintools in Nix flake for macOS

- README.md
- build_sdk.py
People tend to rename the SDK etc and so it helps to have
this file so they know what version they're on.
Also fixes the README for the current layout of the SDK.
> Add VERSION file to SDK layout

- docs/manual.md
- tool/microkit/src/sdf.rs
- tool/microkit/src/sel4.rs
Before this patch, we would default to the platform's smallest page size if it is not explicitly set on a memory region.
However, I have noticed that users of Microkit (including myself) often forget that you can specify the page size of memory region yourself and so if you have a very large memory region, it is much more efficient to use say, 2MB pages, instead of 4K pages.
From this experience, I believe that it is worthwhile to change the default behaviour to select the larget possible page size for the memory region that does not lead to any memory waste. For example, if you have a 4MB sized MR, 2MB page sizes would be used. If you have a 4.1MB sized MR, 4K page sizes would be used.
I cannot think of any reasonable use-case with Microkit currently where people would be relying on this …
> Change default MR page size behaviour

- tool/microkit/src/main.rs
- tool/microkit/src/sdf.rs
- tool/microkit/src/sel4.rs
d7e63d56a911434f6012f14882e8df1a392cfd0f did not consider that the alignment of the memory region in all its mappings matters as well.
Closes https://github.com/seL4/microkit/issues/243.
> tool: fix defaulting to largest page size

- example/imx8mm_evk/passive_server/passive_server.system
- example/tqma8xqp1gb/ethernet/ethernet.system
4574734febed447825756b8618948a731187c7cd changes the SDF for PPCs to be described on a per-channel basis. This patch just updates the examples to adhere to the current SDF.
> Fix examples for channel PPC change

- monitor/src/main.c
- tool/microkit/src/main.rs
- tool/microkit/src/util.rs
Still not 100% ideal as sometimes stack overflows occur multiple pages out-of-bounds of the stack region, but this should be able to catch some of them and save time debugging.
> monitor: report potential stack overflows

- monitor/src/main.c
- tool/microkit/src/lib.rs
- tool/microkit/src/main.rs
- tool/microkit/src/util.rs
I forgot to add this in https://github.com/seL4/microkit/pull/255.
> Name VM TCBs in debug mode as well

- monitor/src/main.c
These need to be visible in the final object and hence should not be static.
This caused an issue with 9a8aba7106a411a1e81df7858ce7a1fc5c26c931 when building in release mode since vm_names is only used in debug mode and so the compiler was (understandably) optimising it out.
> monitor: fix patched variables to not be static

- .github/workflows/sdk.yaml
Right now the tar name will looks something like this: microkit-sdk-1.4.1-dev.52+9a8aba7.tar.gz
for every OS/arch build ~~whereas we want the SDK itself to still be without arch/name but the tar should still include what the target is.~~ changed my mind, all SDK artifacts should include target, even the unpacked version.
> ci: include os/arch in per-commit tar filenames

- README.md
- build_sdk.py
- docs/manual.md
- example/ariane/hello/Makefile
- example/ariane/hello/hello.c
- example/ariane/hello/hello.system
This pull request adds initial support for the CVA6 (formerly Ariane, still known as Ariane in seL4) on the Digilent Genesys 2 FPGA board. It is an open-source RISC-V processor core implementing rv64i.
This change depends on an associated kernel change to re-enable the PLIC, currently in a PR [here](https://github.com/seL4/seL4/pull/1341).
> Added support for Ariane (CVA6) on Digilent Genesys 2 [riscv]

- build_sdk.py
- docs/manual.md
This PR adds support for the Cheshire SoC design implemented on the Digilent Genesys2 FPGA board.
Cheshire is an implementation of the CVA6 core, similarly to Ariane (https://github.com/seL4/microkit/pull/246).
This port depends upon seL4 support in [this PR](https://github.com/seL4/seL4/pull/1354).
> Support for Cheshire on Digilent Genesys 2

- README.md
- build_sdk.py
- tool/microkit/Cargo.toml
- tool/microkit/src/main.rs
- tool/microkit/src/sel4.rs
- tool/microkit/tests/test.rs
One of the things the tool has to do is emulate the kernel boot process, this involves getting a layout of all memory and putting into two categories, 'device' memory and 'normal' memory as defined by the kernel.
The way we do this currently is by looking at certain symbols in the kernel ELF that encode this information. This doesn't work well when the compiler decides to optimise that symbol out and instead embed the information directly into where it's being used in the kernel code.
So, instead we use the `platform_gen.json` file that gets generated by the kernel build system to get the same information.
There should be no difference at all in terms of what the tool actually spits out at the end, it just means that the process of doing this emulation is less fragile.
Closes …
> tool: improve emulation of kernel boot

- loader/src/loader.c
Running qemu with -d guest_errors would previously print out
LDR|INFO: Setting all interrupts to Group 1
LDR|INFO: GICv2 ITLinesNumber: 0x00000000
gic_cpu_write: Bad offset 80
gicv2m_write: Bad offset 4
The first write is supposed to be into the GIC_DIST region, then the second into the GIC_CPU region. Cross referencing to QEMU [1], the GIC addresses in loader.c are incorrect. Now microkit prints:
LDR|INFO: Setting all interrupts to Group 1
LDR|INFO: GICv2 ITLinesNumber: 0x00000008
The generated seL4 devices_gen.h from the DTS is correct, this is purely a microkit issue.
[1]: https://github.com/qemu/qemu/blame/de278e54/hw/arm/virt.c#L164-L165
> loader: fix qemu GIC addresses

- tool/microkit/src/lib.rs
- tool/microkit/src/main.rs
Fixed a couple of bugs related to allocations that are fixed to a particular physical address.
> Fix issues with allocation

- tool/microkit/src/main.rs
Currently `pd_stack_top` is always 16-byte aligned anyways, but just in case anything changes, let's just make sure.
> tool: ensure correct stack pointer alignment

- libmicrokit/include/microkit.h
- libmicrokit/src/dbg.c
- libmicrokit/src/main.c
- tool/microkit/src/main.rs
- tool/microkit/src/sdf.rs
This patch adds error reporting for libmicrokit APIs that make seL4 system calls that do not have an error return value and so the user does not know what went wrong. There is an error message from the kernel, but it refers to cap numbers which a Microkit user would not understand.
Closes https://github.com/seL4/microkit/issues/174.
> libmicrokit: more error reporting

- tool/microkit/src/main.rs
When creating CNodes, the `size` is the (log2) number of CSlots. When creating SchedContexts the `size` is the (log2) size of the object in bytes.
> tool/microkit: fix SchedContext allocation size

- tool/microkit/src/lib.rs
- tool/microkit/src/main.rs
- tool/microkit/src/util.rs
This adds much better error reporting when allocation fails due to a user-error or we have genuinely run out of memory.
The main thing next is to improve the allocator so that we can better utilise the untypeds. There's a couple things it does not that are inefficient but at least now we know when and why an allocation fails.
Closes https://github.com/seL4/microkit/issues/253.
Closes https://github.com/seL4/microkit/issues/250.
> tool: improve error checking and error reporting for allocations

- tool/microkit/src/main.rs
- tool/microkit/src/sdf.rs
A PD will have two sets of mappings in addition to what the user has specified:
1. Mappings for the ELF
2. Mapping(s) for the stack region
Previously, it was possible to accidentally create an overlapping between a user-specified mapping a mapping generated by the tool automatically.
On ARM, this is quite subtle as seL4 allows overwriting existing mappings resulting in no obvious error when this happens.
On RISC-V, this leads to an error upon booting due to seL4 *not* allowing overwriting existing mappings with unmapping first.
> tool: detect overlaps between user-specified maps and generated maps

- CHANGES.md
- loader/src/loader.c
QEMU virt AArch64 won't have U-Boot to initialise the UART for us. QEMU doesn't care and will happily output to the UART even if it's disabled, however if you add `-d guest_errors` to your QEMU invocation, you will get a bunch of QEMU complaints saying you are outputting to the UART while it is disabled. This will fix that.
> loader: cleanup uart_init, do it for QEMU virt AArch64

- build_sdk.py
- docs/manual.md
Previously I did not turn this option on by default because I thought it would make the kernel proofs not apply anymore. In reality this is only true really when a user makes use of the SMC feature. Most users probably will never have to enable it and the ones that that do will no longer have to patch Microkit to enable it.
I've added a warning about using SMC calls in the manual to make users aware of the implications of using this feature.
> Enable "KernelAllowSMCCalls" by default on ARM

- README.md
- build_sdk.py
- docs/manual.md
- loader/Makefile
- loader/src/loader.c
Depends on https://github.com/seL4/seL4/pull/1397.
> Add support for SiFive Premier P550

- docs/manual.md
The html5validator is complaining about duplicate IDs in html produced from the markdown:
- `channel` occurs twice, once explicitly defined and once as a later heading. Rename explicit reference to #channels to match up with heading name.
- `libmicrokit` occurs twice as a heading, one with explicitly defined ID. Rename the second one to #libmicrokit_internals to disambiguate.
> manual: make IDs unique

- build_sdk.py
Most options are duplicated, this cleans it up a bit.
Also with the 'benchmark' config we kept getting warnings saying it's an invalid option on non-ARM architectures so this also fixes that.
Before merging:
> build_sdk.py: cleanup kernel options

- docs/manual.md
- tool/microkit/src/sdf.rs
- tool/microkit/tests/test.rs
From 4KiB to 8KiB. The motivation for this is that while a lot of the PDs that I have dealt with are fine with 4KiB, when developing I use UBSAN which tends to increase stack usage a lot.
Given the small memory footprint (< 50KiB last time I checked) of PDs, I do not think it is an issue to increase the stack size.
As always, memory constrained users could manually set the stack size to 4KiB.
> Increase default PD stack size to 0x2000

- build_sdk.py
- docs/manual.md
- loader/src/loader.c
- platforms.yml
This PR adds Microkit builds for 2gb, 4gb and 8gb versions of the rpi4B.
All rpi4B models have same mini-UART MMIO layout, so we use the same code in loader.c.
Builds successfully on Ubuntu using nix.
> Added builds for extra rpi4B models

- tool/microkit/.cargo/config.toml
Necessary to make macOS -> Linux cross-compilation actually possible without even more dependencies such as a C toolchain.
> tool: use rust-lld for more targets
